data_dir: /
exp_name: NE Pacific Reconstruction
vars_to_reconstruct:
  - tas
time_resolution: 200
maximum_resolution: 200
prior_window: 5200
prior_mean_always_0: false
assimate_together: true
localization_radius: null
percent_of_prior: 100
seed_for_prior: 0
assimilate_selected_seasons:
  - annual
  - summerOnly
  - winterOnly
assimilate_selected_archives:
  - Borehole
  - Coral
  - FluvialSediment
  - GlacierIce
  - GroundIce
  - LakeSediment
  - MarineSediment
  - Midden
  - MolluskShell
  - Other
  - Peat
  - Sclerosponge
  - Shoreline
  - Speleothem
  - TerrestrialSediment
  - Wood
assimilate_selected_region:
  - 48
  - 78
  - 109
  - 174
assimilate_selected_resolution: false
percent_to_assimilate: 100
seed_for_proxy_choice: 0
models_for_prior:
  - hadcm3_regrid
  - trace_regrid
proxy_datasets_to_assimilate:
  - temp12k
age_range_to_reconstruct:
  - 0
  - 12000
reference_period:
  - 3000
  - 5000
age_range_model:
  - 0
  - 22000
reconstruction_type: relative
model_processing: None
assign_seasonality: false
change_uncertainty: false
